"""empty message

Revision ID: 0a4236a7183e
Revises: 
Create Date: 2025-04-08 15:49:42.076236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a4236a7183e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LOD_WORD',
    sa.Column('LODID', sa.String(), nullable=False),
    sa.Column('WORD', sa.String(), nullable=True),
    sa.Column('LEXCAT', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('LODID')
    )
    with op.batch_alter_table('LOD_WORD', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_LOD_WORD_LEXCAT'), ['LEXCAT'], unique=False)
        batch_op.create_index(batch_op.f('ix_LOD_WORD_WORD'), ['WORD'], unique=False)

    op.create_table('LOD_EXAM',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('EX_LODID', sa.String(), nullable=True),
    sa.Column('EXAMPLE', sa.Text(), nullable=True),
    sa.Column('AUDIO', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['EX_LODID'], ['LOD_WORD.LODID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('LOD_USER_FAV',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('USER_ID', sa.String(), nullable=True),
    sa.Column('EX_EXAM_ID', sa.Integer(), nullable=True),
    sa.Column('FAV_DATATIME', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['EX_EXAM_ID'], ['LOD_EXAM.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LOD_USER_FAV')
    op.drop_table('LOD_EXAM')
    with op.batch_alter_table('LOD_WORD', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_LOD_WORD_WORD'))
        batch_op.drop_index(batch_op.f('ix_LOD_WORD_LEXCAT'))

    op.drop_table('LOD_WORD')
    # ### end Alembic commands ###
