"""rename

Revision ID: 218cb0c8e1c9
Revises: 0a4236a7183e
Create Date: 2025-04-08 15:58:42.899757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218cb0c8e1c9'
down_revision = '0a4236a7183e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('LOD_USER_FAV', schema=None) as batch_op:
        batch_op.add_column(sa.Column('FAV_DATETIME', sa.DateTime(), nullable=True))
        batch_op.drop_column('FAV_DATATIME')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('LOD_USER_FAV', schema=None) as batch_op:
        batch_op.add_column(sa.Column('FAV_DATATIME', sa.DATETIME(), nullable=True))
        batch_op.drop_column('FAV_DATETIME')

    # ### end Alembic commands ###
