"""empty message

Revision ID: 9370ce47a043
Revises: 218cb0c8e1c9
Create Date: 2025-04-15 09:58:38.412627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9370ce47a043'
down_revision = '218cb0c8e1c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SDL_CARD',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('AUDIO_URL', sa.String(), nullable=False),
    sa.Column('TRANSCRIPT', sa.Text(), nullable=False),
    sa.Column('TRANSLATION', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SDL_CARD')
    # ### end Alembic commands ###
